### ISSUE TITLE
使われない過去の遺産の式は全て削除する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#10]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/application_controller.rb#L5

@kenko-nokengo これはmasterブランチで本番環境のソースコードと認識してください。開発現場では、本番環境のソースコードは成果物であり、不要なメモを書いてはなりません。
気をつけましょう！

**Comment by kenko-nokengo** [comment]
修正済みです

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
