### ISSUE TITLE
ストロングパラメータ経由にできないか検討する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#11]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/children_controller.rb#L7

@kenko-nokengo 「戻る」ボタンの実装時はストロングパラメータ経由に共通化できないでしょうか？

**Comment by kenko-nokengo** [comment]
```def top_children_question
    if params[:back]
      @children = current_customer.children.build(top_back_params)
    else
      @children = current_customer.children.build
    end
  end
・
・
private
    def top_back_params
      params.permit(:name, :sex, :birthday, :size)
    end
```

戻るボタンをlink_toで実装しているため、ストロングパラメータでparams.require(:child)のようにchildをキーに取得できませんでした。
上記は一応挙動は確認していますが、こんな形ありですか？

**Comment by norotime** [comment]
@kenko-nokengo そういうことですね！許可指定していれば、良いと思います。
formタグの送信ボタンで実装する方法もありますね。

**Comment by kenko-nokengo** [comment]
ありがとうございます！
viewが今でもごちゃごちゃしているので、いったんこれで実装します
