### ISSUE TITLE
renderはaction不要でも動作するためできるだけ短く記述する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#12]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/children_controller.rb#L110

@kenko-nokengo 多種多様な書き方があります。
https://railsguides.jp/layouts_and_rendering.html#%E3%81%BE%E3%81%A8%E3%82%81
しかし、最短経路を辿りましょう！

**Comment by norotime** [comment]
@kenko-nokengo 他も全てチェックしてみてくださいねー。
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/children_controller.rb#L85

**Comment by kenko-nokengo** [comment]
統一しました
