### ISSUE TITLE
何も式のないアクションメソッドは記述しない

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#15]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/sessions_controller.rb#L2

@kenko-nokengo 記述しなくてもViewに処理は流れます。不要なものは書かないようにしましょう。

**Comment by norotime** [comment]
@kenko-nokengo 意図的にオーバーライドしていない限り、です。今回、Deviseクラスは継承していないようだったので、コメントしました。

**Comment by kenko-nokengo** [comment]
修正しました。

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
