### ISSUE TITLE
redirect_toに渡せる引数としてflashを渡す

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#16]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/sessions_controller.rb#L25

@kenko-nokengo 一行で書けると思います。

**Comment by kenko-nokengo** [comment]
修正しました

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
