### ISSUE TITLE
不要なファイルは削除する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#17]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/users_controller.rb#L1

@kenko-nokengo 何かで参照していますか？

**Comment by kenko-nokengo** [comment]
削除しました

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
