### ISSUE TITLE
不要なヘルパーファイルは削除して「何これチェック」を防止する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#18]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/helpers/charges_helper.rb#L1

@kenko-nokengo 他にもチェックをお願いしますね！

**Comment by kenko-nokengo** [comment]
修正済みです

**Comment by norotime** [comment]
@kenko-nokengo 使っていないファイルは、ファイルごと削除してくださいね！
まだ残っています。
