### ISSUE TITLE
プロジェクトに無関係なファイルは削除する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#20]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/User.all#L1

@kenko-nokengo 一見すると大丈夫かな？と思ってしまいます。印象をマイナスに感じてしまうと勿体無いので削除しましょう！

**Comment by kenko-nokengo** [comment]
修正しました

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
