### ISSUE TITLE
プロジェクトに無関係な不要なファイルを削除する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#21]
https://github.com/kenko-nokengo/Wear_kidapp/blob/develop/User.all

**Comment by kenko-nokengo** [comment]
Userは一通り削除したのですが、現状いかがでしょうか？

**Comment by norotime** [comment]
@kenko-nokengo まだmasterには残っていますね。。

**Comment by norotime** [comment]
![2018-03-04 17 47 47](https://user-images.githubusercontent.com/7435505/36943867-32f92ce2-1fd4-11e8-8dff-831ea4c3470e.png)

**Comment by kenko-nokengo** [comment]
あああ、、まだマージしてなかったですね。。。

**Comment by norotime** [comment]
マージしてくださいませね〜

******************************************
株式会社Dive into Code
代表取締役 Founder  CEO
野呂 浩良

TEL 03-5459-1808
携帯 070-3127-8939
FAX 03-5459-1809
noro@ <noro@timeshift.co.jp>diveintocode.jp
http://diveintocode.jp/

〒150-0044
東京都渋谷区円山町２８番４号
大場ビルＡ館２階
※弊社は毎週木曜日が休業日です。

2018-03-04 17:50 GMT+09:00 kengo osawa <notifications@github.com>:
