### ISSUE TITLE
本番環境でのログ肥大化防止のため通常レベルに設定変更する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#5]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/config/environments/production.rb#L52

@kenko-nokengo Railsガイドもご参照くださいーー。
https://railsguides.jp/debugging_rails_applications.html#%E3%83%AD%E3%82%B0%E3%81%AE%E5%87%BA%E5%8A%9B%E3%83%AC%E3%83%99%E3%83%AB

**Comment by kenko-nokengo** [comment]
修正しました

**Comment by norotime** [comment]
@kenko-nokengo どのコミットで修正されていますか？確認したいです〜。イシューをコミットメッセージで紐づけてクローズすると関連づくので、そうして欲しいです！
