### ISSUE TITLE
コメントは例外的な場合のみ記載し、原則は記載せずにコードを読めばわかるようにする

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#6]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/charges_controller.rb#L3

@kenko-nokengo コーディング規約もご覧ください。
http://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html

**Comment by kenko-nokengo** [comment]
修正済みです

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
