### ISSUE TITLE
文字列表記よりもシンボル表記の方が高速なためシンボル表記に統一する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#7]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/addresses_controller.rb#L23

@kenko-nokengo 公式ドキュメントもチェックしましょう！

```
シンボルを使うメリットは

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない
```
https://docs.ruby-lang.org/ja/latest/class/Symbol.html

**Comment by kenko-nokengo** [comment]
修正しました。

**Comment by norotime** [comment]
@kenko-nokengo イシューをコミットでクローズする形にできますか？私がこのイシューを見てもどのコミットかわからないためです。
