### ISSUE TITLE
意味のない不要な空行は削除する

### ISSUE THREAD

**Issue by norotime** [kenko-nokengo/Wear_kidapp#9]
https://github.com/kenko-nokengo/Wear_kidapp/blob/4d24861bbf17c870ab25f4bf9bc09fa7007e79cd/app/controllers/addresses_controller.rb#L27

@kenko-nokengo コーディング規約に忠実になりましょう！守破離です！
http://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html

**Comment by kenko-nokengo** [comment]
修正済みです

**Comment by norotime** [comment]
@kenko-nokengo 完了したらクローズにしてくださいーー。
